version: '3.8'

services:
  db:
    image: postgres:17.4
    container_name: plugapp_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plugapp_db